### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by OnceUponALoop** [Open-Enterprise-OS/oeos#1]
Open Enterprise OS was just the first thing that came to my mind.

We'd need to vote on a replacement name as a community.

A few people suggested the following names in the slack channel

- Open Enterprise OS (OEOS)
- Second Community Enterprise Operating System (ScentOS)
- Float Enterprise Linux (FEL)

I agree with this comment from Stephen LePage
> From a naming perspective, I would like to see emphasis on the Community aspect.

**Comment by hbjydev** [comment]
I think ScentOS is a little too close to CentOS personally. Might bodge any SEO we get.

I also think we should keep EL in the name, to ensure people could easily throw it in the same ballpark as RHEL, perhaps even assume it's a RHEL derivative right from the name.

**Comment by destroyer998** [comment]
Barry S on slack suggested: ChapOS

**Comment by nazunalika** [comment]
**OpenEL** was suggested on slack.

**Comment by OnceUponALoop** [comment]
Open Enterprise Linux would mismatch Oracle Enterprise Linux (another rhel clone)

**Comment by nazunalika** [comment]
> 
> 
> Open Enterprise Linux would mismatch Oracle Enterprise Linux (another rhel clone)

I understand how that can be conflated, but how though? CentOS isn't named COS. OpenEL would be the name, and Open and Oracle do not match.

**Comment by hbjydev** [comment]
It's a shame OpenEL is taken, that would be a pretty good distro name for this imo

**Comment by hbjydev** [comment]
Kurt in Slack suggested "Delta", because that's where CentOS 8 ends.

**Comment by OnceUponALoop** [comment]
Close this and move to #6 per suggestion on slack
